(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"index_atlas_1", frames: [[0,0,1068,225],[1070,0,494,246],[1566,0,311,121]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.big2 = function() {
	this.initialize(ss["index_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.logopd1 = function() {
	this.initialize(ss["index_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.small1 = function() {
	this.initialize(ss["index_atlas_1"]);
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Tween14 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1E2130").s().p("EhtyAchMAAAg5CMDblAAAMAAAA5Cg");
	this.shape.setTransform(0.025,0,3,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2108,-182.5,4216.1,365.1);


(lib.Tween13 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1E2130").s().p("EhsJAeAMAAAg8AMDYTAAAMAAAA8Ag");
	this.shape.setTransform(0.025,0,3,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2076.5,-192,4153.1,384.1);


(lib.Tween12 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACAA7IgDgBIgBgDIAAgMIguAAIAAAMIgBADIgDABIgMAAIgCgBIgBgDIAAgYIABgDIACgBIACAAQADAAADgDQADgFAAgIIABgTIAAgUQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABgBIACgBIA0AAIACABIABADIAAA3IAHAAIACABIABADIAAAYIgBADIgCABgABdgHQAAANgCAIQgCAKgDADIAcAAIAAgrIgVAAgAH6AjQgJgIgBgSIAAgEIAAgEQAAgIAFgJQAEgIAIgFQAJgEAKAAQAMAAAIAFQAHAFAFAIQAEAKAAAJIAAAEIgBACIgDABIgwAAIAAABIACAJQABAFAEACQAEADAFAAQAEAAADgCIAEgCIAFgFIACgBIANAAIACABIABADIgDAFQgDAFgDACQgFAEgGACQgIACgGAAQgQAAgKgKgAILgRQgEACgBAEQgCAEAAAGIAAABIAgAAIAAgBQAAgGgCgEQgCgEgDgCQgEgDgFAAQgFAAgEADgAFfAoQgIgDgFgIQgEgHgBgLIAAgLQABgLAEgGQAEgIAJgEQAGgEAMAAQALAAAFACQAFADAGAEQAEAEACAEQACAEAAAEIgBACIgCABIgNAAIgCAAIgCgCQgCgGgEgDQgDgCgGAAQgHAAgEAEQgFAFAAAJIAAAKQAAAKAFAFQAEAFAHgBQAGABAEgDQADgDACgGIACgBIACgBIANAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAABAAAAIABACIgBAGQgBACgDAFIgHAGQgDADgHACQgEACgJAAQgKAAgIgFgAgGAoQgIgEgEgHQgEgIgBgKIAAgLQABgLAEgGQAEgIAIgEQAHgEAMAAQAMAAAHAEQAHADAFAJQAEAGABALIAAALQgBALgEAHQgDAHgJAEQgJAFgKAAQgMAAgHgFgAABgOQgEAFAAAJIAAAFIAAAGQAAAJAEAFQAEAFAIAAQAHAAAFgFQADgFABgJIAAgLQAAgJgEgFQgFgFgHAAQgHAAgFAFgAlRAjQgJgJgBgRIAAgIQABgJAEgIQAEgJAIgEQAJgEAJAAQAMAAAIAFQAJAFADAIQAEAIAAALIAAAEIgBACIgCABIgxAAIAAABIACAJIAGAHQAEADAEAAQAEAAADgCIAFgCIAEgFIADgBIAMAAIACABIABADIgCAFQgDAFgEACQgEAEgGACQgIACgHAAQgQAAgJgKgAlAgRQgEACgCAEQgCAGAAAEIAAABIAhAAIAAgBQAAgEgCgGQgDgFgDgBQgEgDgFAAQgEAAgEADgAHYArIgCAAIgCgCIgTgdIgLAAIAAAbIgBADIgCABIgMAAIgCgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAhDQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABgBIACgBIAMAAIACABIABADIAAAaIALAAIASgbIABgCIADgBIANAAIACABIABACIAAABIgBABIgVAeIAYAjIABACIgBACIgCABgAEuArIgCgBIgBgDIAAgtIgjAuIgCACIgCABIgLAAIgCgBIgBgDIAAhDIABgDIACgBIAMAAIADABIABADIAAAuIAjgvIABgCIADgBIALAAIACABIABADIAABDQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgCABgADSArIgCgBIgBgDIAAg3IgfAAIAAA3IgBADIgDABIgMAAIgCgBIgBgDIAAhDIABgDIACgBIA+AAIADABIABADIAABDIgBADIgDABgAg3ArIgDgBIgBgDIAAg3IgfAAIAAA3IgBADIgCABIgMAAIgDgBIgBgDIAAhDIABgDIADgBIA+AAIACABQAAABABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAABDQAAABAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgCABgAjfArIgDgBIgBgDIAAhDIABgDIADgBIAgAAQAQAAAHAGQAHAFAAAKQAAAGgCAEQgDACgEACQAFACADAFQADAGAAAFQAAALgIAFQgIAGgOAAgAjQAeIARAAQAGAAAEgDQADgCAAgEQAAgFgDgCQgEgCgGgBIgRAAgAjQgBIARAAQAGAAADgCQADgDAAgEQAAgFgDgBQgEgCgFAAIgRAAgAl2ArIgDgBIgCgBIgTgdIgJAAIAAAbIgBADIgCABIgMAAIgCgBIgBgDIAAgbIgJAAIgUAdIgBABIgDABIgOAAIgCgBIgBgCIAAgCIAYgjIgVgeIAAgBIAAgBIABgCIACgBIANAAIACABIACACIASAbIAJAAIAAgaIABgDIACgBIAMAAIACABIABADIAAAaIAJAAIASgbIABgCIADgBIANAAIACABIABACIgBACIgVAeIAZAjIAAACIgBACIgCABgAomArIgDgBIgBgDIAAgLIABgCIADgBIAFAAQAEAAADgBIAGgGIACgEIglhEIABgDIACgBIAPAAIACABIABACIAaAwIAVgwIACgCIACgBIAOAAIACABIABACIAAACIglBQIgHAJQgDADgGADQgFABgHAAg");
	this.shape.setTransform(-89.275,-1.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#A60000").s().p("AgMAOQgGgGAAgIQAAgHAGgFQAFgGAHAAQAIAAAGAGQAFAFAAAHQAAAIgFAGQgGAFgIAAQgHAAgFgFg");
	this.shape_1.setTransform(56.675,-8.775);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag4AyIAAhjIBxAAIAAAWIhZAAIAAARIBOAAIAAAVIhOAAIAAARIBZAAIAAAWg");
	this.shape_2.setTransform(47.775,-1.825);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag6AyIAAhjIBRAAQAQAAAHAGQAHAHAAAOIAAACQAAAIgCAEQgCAFgFACIAIACQAHAGAAAOIAAACQAAAOgHAHQgHAGgQAAgAghAcIA6AAQAGAAABgBQACgCAAgEIAAgDQAAgEgCgCQgBgCgGAAIg6AAgAghgJIA0AAQAGAAABgCQACgBAAgFIAAgDQAAgEgCgBQgBgCgGAAIg0AAg");
	this.shape_3.setTransform(34.875,-1.825);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgcAyQgIAAgFgBQgGgCgEgEQgEgEgBgFQgCgFAAgJIAAhFIAZAAIAABGQAAAEACACQACABAFAAIAxAAQAFAAACgBQACgCAAgEIAAhGIAZAAIAABFQAAAJgCAFQgBAFgEAEQgEAEgFACQgFABgJAAg");
	this.shape_4.setTransform(21.275,-1.825);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgLAyIAAhNIgvAAIAAgWIB1AAIAAAWIgvAAIAABNg");
	this.shape_5.setTransform(7.625,-1.825);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgcAyQgIAAgGgBQgFgCgEgEQgEgEgBgFQgCgFAAgJIAAhFIAZAAIAABGQAAAEACACQACABAFAAIAxAAQAFAAACgBQACgCAAgEIAAhGIAZAAIAABFQAAAJgCAFQgCAGgDADQgFAFgFABQgFABgIAAg");
	this.shape_6.setTransform(-6.025,-1.825);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAgAyIgVggIgtAAIAAAgIgZAAIAAhjIBXAAQAHAAAGABQAGADADADQAFAFABAEQABAGAAAIIAAAHQAAAOgFAHQgFAHgLABIAYAhgAgigEIA5AAQAGAAABgBQACgCAAgEIAAgJQAAgEgCgBQgBgCgGAAIg5AAg");
	this.shape_7.setTransform(-18.925,-1.825);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AANAdIgNgNIgMANQgEADgEAAQgFAAgDgDQgDgEAAgEQAAgFADgDIANgNIgNgMQgDgEAAgEQAAgFADgDQADgDAFAAQAEAAAEADIAMANIANgNQADgDAFAAQAEAAAEADQADADAAAFQAAAEgDAEIgNAMIANANQADADAAAFQAAAEgDAEQgEADgEAAQgFAAgDgDg");
	this.shape_8.setTransform(64.025,-1.975);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFF4F5").s().p("AjqA0QgRAAgLgDIAAADIgGAAQgzAAgJgYIAAAVQgigHAAgaIAAgBIBDAAQABAPAeAAIABAAIAAgPIABAAQACAPAdAAIACAAQAUAAAGgDQAFgCABgFQAAgFgFgCQgGgDgRAAIgSgBQgLAAgIgBIAAACIgPgBQgugBgFgVIAAAVQghgGABgVIAAgBQgBgXAhgGIAAAWQAGgYAzAAIAJAAIAAACQAKgCAOAAIAKAAQAUAAAMADQAeAHAAAWIAAABIgjAAQgBgMgdAAIgCAAQgcAAAAAJQAAAIAYAAIApACQAhAFABAWIAAACQgBAaghAGQgLACgSAAgAkmgVQgBAIAZAAIAHAAIAAgRIgEAAQgcAAABAJgAEcAyIAAhLIguAAIAAgYIB9AAIAAAYIguAAIAABLgADGAyIAAgSQAAgJgFgEQgFgEgMAAIgsAAIAAAjIghAAIAAhjIBWAAQAuAAAAAaIAAABQAAAKgGAGQgGAFgJAAIAAACQAIAAAHAHQAGAHAAAJIAAAagACEgHIAzAAQANAAAAgKQAAgJgNAAIgzAAgAA6AyIgKgSIg/AAIgKASIgiAAIA2hjIAqAAIA5BjgAAkAJIgTgiIgDAAIgSAiIAoAAgAh1AyIAAhLIguAAIAAgYIB9AAIAAAYIguAAIAABLg");
	this.shape_9.setTransform(109.75,-2.275);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-146,-10.7,292.1,15.299999999999999);


(lib.Tween11 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1E2130").s().p("EhlEAcnMAAAg5NMDKIAAAMAAAA5Ng");
	this.shape.setTransform(0.0412,0,3.4399,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2225.1,-183.1,4450.299999999999,366.2);


(lib.Tween9 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AEDB5QgEAAgBgCQgDgDAAgCIAAgaIheAAIAAAaQAAACgDADQgBACgEAAIgYAAQgEAAgBgCQgDgDAAgCIAAgzQAAgCADgDQABgCAEAAIACAAQAIAAAFgIQAEgIADgRQACgPAAgbIAAgoIACgFQACgCAEAAIBqAAQADAAACACQACACAAADIAABzIANAAQAEAAABACQADACAAADIAAAzQAAACgDADQgBACgEAAgAC7gPQAAAcgEAQQgDARgHAKIA6AAIAAhbIgsAAgAQSBIQgUgTgBgkIgBgHIABgHQAAgVAKgRQAJgRAQgIQAQgJAWAAQAYAAARAKQAQAJAIATQAJAQAAAYIAAAGQAAADgCACQgCACgEAAIhjAAIAAACQAAAKAEAKQAEAJAHAFQAIAFAKAAQAIAAAGgCIAJgGIAJgKIAFgBIAaAAQABAAABAAQAAABABAAQAAAAABAAQAAABABAAQAAABABAAQAAABAAAAQABABAAAAQAAABAAABQgBAFgEAGQgFAHgJAHQgHAGgOAFQgOAEgQAAQgiAAgSgTgAQ0glQgIAFgDAJQgEAHAAANIAAABIBCAAIAAgBQAAgLgEgJQgDgJgIgFQgIgFgKAAQgJAAgJAFgALMBTQgRgJgJgOQgJgQgBgWIAAgXQABgUAJgRQAJgPARgIQAPgIAWAAQATAAAOAFQANAGAJAIQAJAIAEAJQAEAHABAIQAAAEgCACIgFACIgbAAIgFgCIgDgEQgEgMgHgFQgHgFgMAAQgPAAgJAJQgIAJgBAUIAAAVQABAUAIAKQAJAJAPAAQAMAAAHgFQAHgFAEgMIADgEIAFgCIAbAAQADAAACACQACACAAADIgDAMQgCAFgGAJQgFAHgJAGQgJAGgLADQgLAEgRAAQgWAAgPgIgAgRBTQgRgKgHgOQgJgQgBgUIAAgZQABgTAJgQQAJgPAQgJQAQgIAXAAQAWAAARAIQAQAJAJAPQAJAOABAVIAAAZQgBAWgJAOQgIAPgQAJQgQAIgYAAQgYAAgQgIgAgBgeQgIAKgBAUIAAAWQABAUAIAJQAHAKARAAQAQAAAIgKQAJgKABgTIAAgWQgBgTgJgLQgJgKgPAAQgQAAgIAKgAq4BIQgTgTgCgkIAAgOQACgWAJgQQAJgRAQgIQAQgJAWAAQAXAAARAKQARAKAIASQAJASAAAWIAAAGQAAACgDADQgBACgEAAIhjAAIAAACQAAAJAEALQAEAIAHAGQAIAFAKAAQAHAAAHgCIAJgGIAFgGIAEgEIAFgBIAaAAQADAAACACQAAABABAAQAAABAAAAQAAABAAABQAAAAAAABQAAAEgFAHQgEAHgJAHQgJAGgNAFQgNAEgQAAQgiAAgTgTgAqVglQgIAFgDAJQgEAHAAANIAAABIBCAAIAAgBQAAgNgEgHQgDgJgIgFQgJgFgJAAQgKAAgIAFgAPFBYIgFgBIgEgEIgng6IgVAAIAAA4QAAACgDADQgBACgEAAIgYAAQgDAAgCgCQgCgCAAgDIAAiMQAAgDACgCQACgCADAAIAYAAQAEAAABACQADACAAADIAAA1IAVAAIAkg4IADgDQADgBADAAIAaAAQADAAACABQABABAAAAQAAAAAAABQABABAAAAQAAABAAAAIgBACIgsBCIAyBIQAAAAAAABQABAAAAAAQAAABAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAQgBAAAAAAgAJpBYQgEAAgCgCQgBgCAAgDIAAhfIhIBhIgDADQgCACgDAAIgXAAQgDAAgCgCIgCgFIAAiMIACgFQACgCAEAAIAYAAQAEAAABACQACACAAADIAABgIBIhjIADgDIAFgBIAXAAQADAAACACIACAEIAACNIgCAFQgCACgDAAgAGsBYQgDAAgCgCIgCgFIAAh0IhAAAIAAB0QAAACgCADQgCACgDAAIgZAAQgDAAgCgCQgCgDAAgCIAAiMQAAgDACgCQACgCADAAICAAAQADAAACACQACACAAADIAACMQAAACgCADQgCACgDAAgAh1BYQgDAAgCgCQgCgCAAgDIAAh0IhAAAIAAB0IgCAFQgCACgDAAIgZAAQgDAAgCgCQgCgCAAgDIAAiMQAAgDACgCQACgCADAAIB/AAQAEAAACACIACAFIAACMIgCAFQgCACgEAAgAnOBYQgEAAgBgCQgDgDAAgCIAAiMQAAgDADgCQABgCAEAAIBCAAQAfAAAQALQAPAMAAAUQAAANgFAGQgGAHgHAEQAKAFAGAKQAGAKAAALQAAAVgQAMQgPAMggAAgAmvA9IAjAAQAMAAAIgEQAHgFAAgJQAAgKgHgFQgGgEgOAAIgjAAgAmvgDIAiAAQAMAAAHgFQAHgFAAgJQAAgKgHgEQgHgDgMAAIgiAAgAsEBYQgDAAgDgCIgDgDIgng6IgSAAIAAA4QAAADgCACQgCACgDAAIgYAAQgEAAgCgCIgCgFIAAg4IgSAAIgnA6IgDADQgCACgEAAIgeAAIgEgCQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAIACgEIAxhIIgshCIAAgCQAAAAAAgBQAAAAAAgBQAAgBABAAQAAAAAAgBQABAAAAAAQABgBAAAAQABAAAAAAQABAAABAAIAaAAQAEAAACABIADADIAkA4IASAAIAAg1IACgFQACgCAEAAIAYAAQADAAACACQACACAAADIAAA1IARAAIAlg4IADgDQADgBADAAIAaAAQABAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAABABAAQAAAAAAABQABABAAAAQAAABAAAAIgBACIgsBCIAyBIIABAEQAAAAAAABQAAAAgBABQAAAAAAAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAQgBAAAAAAgAxsBYQgEAAgBgCQgDgDAAgCIAAgWQAAgDADgDQABgCAEAAIALAAQAHAAAIgDQAGgEAFgIIAFgIIhMiKIgBgDQAAgBAAgBQAAAAABgBQAAAAAAgBQABAAAAgBQABAAAAgBQABAAAAAAQABgBABAAQAAAAABAAIAdAAQABAAAAAAQABAAABABQAAAAABAAQAAAAABABQACABABADIA1BiIArhiQABgEACAAIAFgCIAcAAQAAAAABAAQABAAAAABQABAAAAAAQAAAAABABQAAAAABABQAAAAABAAQAAABAAABQAAAAAAABIAAADIhLCmQgHAMgIAHQgHAHgLAEQgKADgPAAg");
	this.shape.setTransform(0.025,24.575);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-116.7,12.5,233.5,24.200000000000003);


(lib.Tween8 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFF4F5").s().p("AlrBQQgYAAgTgEIAAAEIgJAAQhMAAgQglIAAAhQg0gKAAgqIAAgBIBnAAQABAYAvAAIABAAIAAgYIABAAQADAYAvAAIACAAQAeAAAKgFQAIgEAAgHQAAgIgGgDQgKgFgaAAIgdgBQgPAAgOgCIAAACIgWAAQhGgBgJghIAAAgQgygJAAghIAAgCQAAgjAygJIAAAiQAJglBQAAIAMAAIAAADQASgDAUAAIAPAAQAfAAASAFQAvAJAAAjIAAACIg1AAQgDgTgtAAIgEAAQgaAAgKAFQgGACAAAHQAAANAmAAIAcAAQASABAQACQA0AHAAAjIAAADQAAASgKALQgMAPgeAFQgVADgXAAgAnBgqQgGACAAAHQAAAFAGAEQAJAEAXAAIAKAAIAAgbIgGAAQgaAAgKAFgAG1BNIAAh1IhHAAIAAgkIDCAAIAAAkIhHAAIAAB1gAExBNIAAgbQAAgPgIgGQgHgGgUAAIhDAAIAAA2IgzAAIAAiZICEAAQBHgBABAoIAAACQAAAPgKAJQgJAJgOAAIAAAEQANAAAKALQAKAKAAANIAAApgADLgLIBPAAQAUAAAAgPIAAgBQAAgOgUAAIhPAAgABZBNIgPgcIhiAAIgPAcIg1AAIBTiZIBCAAIBXCZgAA3AOIgeg2IgDAAIgcA2IA9AAgAi2BNIAAh1IhHAAIAAgkIDCAAIAAAkIhHAAIAAB1g");
	this.shape.setTransform(94.6,22.7375,1.25,1.25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAUAtIgUgVIgTAVQgFAFgIAAQgHAAgFgFQgFgFAAgHQAAgHAFgGIAUgUIgUgTQgFgFAAgHQAAgHAFgGQAFgFAHAAQAIAAAFAFIATAVIAUgVQAFgFAHAAQAHAAAFAFQAGAGAAAHQAAAHgGAFIgUATIAUAUQAGAGAAAHQAAAHgGAFQgFAFgHAAQgHAAgFgFg");
	this.shape_1.setTransform(6.3813,23.2688,1.25,1.25);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#A60000").s().p("AgUAVQgJgJAAgMQAAgLAJgJQAIgIAMgBQAMABAJAIQAJAJAAALQAAAMgJAJQgJAJgMAAQgMAAgIgJg");
	this.shape_2.setTransform(-7.775,10.2375,1.25,1.25);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhXBOIAAiaICvAAIAAAhIiJAAIAAAbIB3AAIAAAhIh3AAIAAAaICJAAIAAAjg");
	this.shape_3.setTransform(-24.9625,23.6125,1.25,1.25);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhaBOIAAiaIB+AAQAXAAALAKQAMAKAAAVIAAAEQAAALgEAHQgDAHgHAEIALADQAMAJAAAXIAAACQAAAWgMALQgLAJgXABgAgzArIBaAAQAIAAADgCQADgDAAgGIAAgFQAAgGgDgDQgDgDgIABIhaAAgAgzgPIBQAAQAJAAACgCQADgCAAgHIAAgFQAAgGgDgDQgCgDgJAAIhQAAg");
	this.shape_4.setTransform(-49.8062,23.6125,1.25,1.25);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgrBOQgMgBgKgCQgJgDgFgGQgFgEgDgKQgCgHAAgOIAAhrIAmAAIAABsQAAAGACADQADACAIAAIBNAAQAIAAACgCQADgDAAgGIAAhsIAnAAIAABrQgBAMgCAJQgCAHgGAHQgGAGgJADQgJACgLABg");
	this.shape_5.setTransform(-76.025,23.6125,1.25,1.25);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgSBOIAAh5IhJAAIAAghIC3AAIAAAhIhJAAIAAB5g");
	this.shape_6.setTransform(-102.3687,23.6125,1.25,1.25);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgsBOQgLgBgKgCQgJgEgEgFQgHgEgCgKQgDgHAAgOIAAhrIAnAAIAABsQAAAFADAEQACACAIAAIBNAAQAIAAADgCQACgEAAgFIAAhsIAmAAIAABrQAAAOgCAHQgCAJgGAFQgFAFgJAEQgKACgMABg");
	this.shape_7.setTransform(-128.7125,23.6125,1.25,1.25);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAyBOIgigzIhFAAIAAAzIgnAAIAAiaICGAAQAMAAAJACQAJADAGAGQAGAGACAHQACAJAAANIAAALQAAAWgHALQgIAKgRACIAlA0gAg1gGIBZAAQAIAAADgDQADgCAAgHIAAgNQAAgGgDgDQgDgDgIAAIhZAAg");
	this.shape_8.setTransform(-153.5562,23.6125,1.25,1.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-165.1,6.6,329.7,26.699999999999996);


(lib.Tween7 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjnA5QgVgSAAglIAAgDQAAglAVgRQAXgTAiABQAigBAWATQAWARAAAlIAAADQAAAlgWASQgWARgiAAQgjAAgWgRgAjHghQgKAIAAATIAAANQAAATAKAJQAJAJAQAAQAQAAAJgJQAKgIAAgUIAAgNQAAgTgKgIQgJgJgQAAQgRAAgIAJgApXA5QgVgRAAglIAAgEQAAgmAVgQQAXgSAiAAQAiAAARAMQATANADAeIAAAEIgrAAIAAgFQgCgNgHgEQgHgGgNAAQgRABgJAHQgJAJAAATIAAANQAAAXAJAGQAJAIARAAQAPgBAHgGQAHgHAAgKIAAgEIArAAIAAAEQgBAcgTAOQgTANgigBQgjAAgWgRgAHtBIIAAiPIApAAIAAAsIAiAAQAdAAAMAOQAMANAAAWQAAAZgMAMQgNANgcAAgAIWAoIAdAAQAIAAAEgEQAFgEgBgKQABgIgFgFQgFgFgHAAIgdAAgAGDBIIAAhtIguAAIAAgiICHAAIAAAiIgvAAIAABtgADWBIIAAiPIBzAAIAAAiIhKAAIAAAVIBAAAIAAAeIhAAAIAAAZIBLAAIAAAhgABBBIIAAiPIBMAAQAaAAAOANQAOANABAaQgBAYgOAMQgNANgcAAIghAAIAAAqgABrAAIAbAAQALAAAEgEQAFgGAAgJQAAgLgFgFQgEgEgLAAIgbAAgAgnBIIAAhtIgvAAIAAgiICGAAIAAAiIguAAIAABtgAk7BIIAAhQIAAgHIAAAAIgEAOIgfBJIggAAIghhMIgEgNIgBAAIABANIAABMIgiAAIAAiPIA1AAIAjBSIABAGIABAAIADgNIAghLIA2AAIAACPg");
	this.shape.setTransform(-0.725,-1.9125,1.25,1.25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#1E252F").s().p("A3cEIQhtABhNhOQhOhOAAhtQAAhtBOhNQBNhOBtAAMAu5AAAQBtAABNBOQBOBNAABtQAABthOBOQhNBOhtgBg");
	this.shape_1.setTransform(-0.375,-0.15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-176.8,-26.6,352.9,52.900000000000006);


(lib.Tween6 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1E2130").s().p("EmqdAhAMAAAhB/MNU7AAAMAAABB/g");
	this.shape.setTransform(0,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2729.4,-211.1,5458.8,422.29999999999995);


(lib.Symbol26 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1E2130").s().p("EhhpATiMAAAgnDMDDTAAAMAAAAnDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol26, new cjs.Rectangle(-625,-125,1250,250), null);


(lib.Symbol25 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1E2130").s().p("EhhpATiMAAAgnDMDDTAAAMAAAAnDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol25, new cjs.Rectangle(-625,-125,1250,250), null);


(lib.Symbol23 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_4
	this.instance = new lib.small1();
	this.instance.setTransform(-148,-112);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol23, new cjs.Rectangle(-148,-112,311,121), null);


(lib.Symbol4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1E2130").s().p("ElIHATiMAAAgnDMKQPAAAMAAAAnDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(-2100,-125,4200,250), null);


(lib.logopdsmall = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.instance = new lib.logopd1();
	this.instance.setTransform(-57,-39,0.3,0.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-57,-39,148.2,73.8);


(lib.logopd = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.instance = new lib.logopd1();
	this.instance.setTransform(-93,-62,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-93,-62,247,123);


(lib.Group = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhWBgIAAgSQgKgBgGgHQgGgHAAgMIAAgCQAAgMAGgHQAGgIAKAAIAAgUIAFAAIAAAUQAKAAAGAIQAHAHAAAMIAAACQAAAMgHAHQgGAHgKABIAAASgAhRBJQAHAAAFgHQAFgFAAgKIAAgDQAAgJgFgGQgEgEgIgBgAhiAhQgFAGAAAJIAAADQAAAKAFAFQAFAHAHAAIAAgtQgHAAgFAFgAvOBgIAAgSQgJgBgHgHQgGgIAAgLIAAgCQAAgMAGgHQAHgIAJAAIAAgUIAGAAIAAAUQAJAAAHAIQAGAIAAALIAAACQAAALgGAIQgHAIgJAAIAAASgAvIBJQAHAAAFgHQAFgGAAgJIAAgDQAAgIgFgHQgFgEgHgBgAvaAhQgEAGAAAJIAAADQAAAKAEAFQAGAHAGAAIAAgtQgHABgFAEgAw4BgIAAhJIAGAAIAAAHQADgEACgBQAEgCAFgBQAIABAFAHQAEAIAAALIAAACQAAAMgFAHQgEAIgIgBQgDAAgFgCQgEgBgCgDIAAAZgAwtAeIgFAGIAAAdIAEAFQADACAFAAQAHAAADgGQADgGAAgJIAAgDQAAgJgDgGQgEgFgGAAQgFAAgCACgAodBaIAAgOIglAAIAAAOIgFAAIAAgSIAFAAQACgEABgDIACgqIAfAAIAAAxIAHAAIAAASgAo5AzQAAAKgBAEIgCAHIAZAAIAAgrIgVAAgACLBUIACgEIABgGIAAgJIAGAAIAAAJQAAAEgBADQgCAFgCABgAi8BUIADgEIAAgPIAHAAIAAAJQAAAEgCADQgCAFgCABgAlsBUIADgEIABgGIAAgJIAGAAIAAAJQAAAEgCADIgEAGgAppBUIADgEIABgGIAAgJIAGAAIAAAJQAAAEgCADIgEAGgAQHBJQgFgGAAgKQAAgGADgEQADgFAFgCIAAgBQgEgBgDgFQgDgEAAgGQAAgIAFgGQAGgFAHgBQAHABAGAFQAFAFAAAJQAAAGgDAEQgCAFgFABIAAABQAFACADAFQAEAEAAAGQAAAKgGAGQgGAFgIAAQgIAAgGgFgAQLAvQgEAEAAAGQAAAIAEADQAEAFAGAAQAGAAAEgFQAEgEAAgHQAAgFgEgFQgEgEgGgBQgGABgEAEgAQMANQgDAEAAAGQAAAFADAFQADAFAGAAQAFAAAEgFQADgEAAgGQAAgGgDgEQgDgEgGAAQgGAAgDAEgAOKBIQgFgFAAgLIAAgeQAAgLAFgFQAEgHAJAAQAJAAAFAHQAEAFAAALIAAAeQAAAKgEAGQgFAGgJAAQgJAAgEgGgAOOANQgDAFAAAIIAAAeQAAAHADAFQADAEAGABQAGgBAEgEQADgFAAgHIAAgeQAAgIgDgFQgEgEgGAAQgGAAgDAEgAM0BJQgGgGAAgKQAAgFADgFQAEgFAFgCIAAgBQgEgBgDgFQgDgEAAgGQAAgIAFgGQAFgFAIgBQAHABAFAFQAFAFAAAJQAAAGgDAEQgCAFgFABIAAABQAGACADAFQADAEAAAGQAAAKgFAGQgHAFgHAAQgJAAgFgFgAM3AvQgDAEAAAGQAAAIADADQAEAFAHAAQAGAAAEgFQAEgEAAgHQAAgFgEgFQgEgEgGgBQgHABgEAEgAM5ANQgEAEAAAGQAAAFAEAFQADAFAGAAQAFAAAEgFQADgEAAgGQAAgGgDgEQgEgEgFAAQgHAAgCAEgALcBJQgGgGAAgJIAAgBIAGAAIAAABQAAAGAEAEQACAFAHAAQAGAAAEgFQAEgFAAgGQAAgIgFgDQgEgEgGAAIgGAAIAAgFIAFAAQAGAAAEgEQADgEAAgGQAAgGgDgFQgDgDgFAAQgFAAgDADQgDAEAAAGIAAABIgGAAIAAgBQAAgIAFgFQAFgGAHAAQAIABAEAFQAFAGAAAHQAAAHgDADQgCAFgFACQAFACAEAEQADAEAAAIQAAAKgFAGQgGAFgIAAQgIAAgFgFgAKyBIQgFgGAAgKIAAgeQAAgLAFgFQAEgHAJAAQAJAAAFAHQAFAFAAALIAAAeQAAALgFAFQgFAGgJAAQgJAAgEgGgAK2ANQgDAFAAAIIAAAeQAAAHADAFQADAEAGABQAHgBADgEQADgFAAgHIAAgeQAAgIgDgFQgDgEgHAAQgGAAgDAEgAC4BEQgGgIAAgSIAAgDQAAgRAGgJQAHgKAKAAQAKAAAGAKQAHAIAAASIAAADQAAASgHAIQgGAKgKAAQgKAAgHgKgAC8ARQgFAHAAAPIAAAEQAAAPAFAHQAEAIAJAAQAIAAAEgIQAFgHAAgPIAAgEQAAgPgFgHQgEgIgIAAQgJAAgEAIgAiSBHQgFgIAAgMIAAgCQAAgMAFgIQAGgHAJAAQAJAAAFAHQAFAIAAAMIAAACQAAAMgFAIQgFAHgJAAQgJAAgGgHgAiOAhQgDAGAAAJIAAADQAAAKADAFQAEAHAHAAQAHAAADgHQAEgFAAgKIAAgDQAAgJgEgGQgDgFgHAAQgHAAgEAFgAlDBJQgFgFAAgIIAAAAIAGAAIAAAAQAAAGADADQADAEAFAAQAHgBAEgFQADgFAAgKIgRAAIAAgFIARAAQAAgJgDgFQgEgGgHABQgFAAgDACQgDAEAAAFIAAABIgFAAIAAgBQAAgHAEgFQAGgEAGgBQAKAAAFAHQAFAJAAALIAAABQAAAMgFAJQgFAHgKAAQgHAAgFgFgAnqBJQgFgGAAgJIAAAAIAFAAIAAAAQAAAHAEADQADAFAHAAQAGgBADgEQAEgGAAgIQAAgJgEgFQgEgEgFAAQgDAAgEADIgFAFIgFgDIADgkIAeAAIAAAGIgZAAIgDAaIAGgFIAHgBQAHAAAGAGQAFAFAAAMQAAAKgGAIQgFAGgIAAQgIAAgGgFgAsABHQgFgIAAgMIAAgCQAAgMAFgIQAFgHAJAAQAIAAAEAGQAFAFAAAHIAAABIgGAAIAAgBQAAgGgCgDQgDgDgGAAQgGAAgEAFQgDAGAAAJIAAADQAAAKADAFQAEAHAGAAQAGgBADgDQACgDAAgHIAAAAIAGAAIAAAAQAAAIgFAGQgEAFgIAAQgIAAgGgHgAtUBHQgFgIAAgMIAAgCQAAgLAFgJQAFgHAKAAQAJAAAFAHQAFAJAAALIAAACQAAAMgFAIQgFAHgJAAQgJAAgGgHgAtQAhQgDAGAAAJIAAADQAAAKADAFQAEAHAHAAQAHAAADgHQAEgGAAgJIAAgDQAAgHgEgIQgDgFgHAAQgHAAgEAFgAupBHQgGgIAAgMIAAgCQAAgLAGgJQAFgHAJAAQAJAAAFAHQAGAJAAALIAAACQAAAMgGAIQgFAHgJAAQgJAAgFgHgAumAhQgDAIAAAHIAAADQAAAJADAGQAEAHAHAAQAHAAADgHQAEgGAAgJIAAgDQAAgIgEgHQgDgFgHAAQgHAAgEAFgAq4BKQgEgFAAgHQAAgIAFgFQAFgDAHAAIALAAIAAgGQAAgGgCgEQgDgDgFAAQgEAAgEADQgCADAAAFIAAABIgFAAIAAgBQAAgGAEgFQAEgEAIgBQAHAAAEAFQAEAEAAAJIAAAZIABAKIAAABIgFAAIgCgHQgBADgEADQgEACgFAAQgGAAgEgDgAqzA1QgEADAAAGQAAAFADACQACAEAFAAQAEgBAFgDQAEgEAAgFIAAgKIgKAAQgGAAgDADgAReBLQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAAAgBgBgAOzBLQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAAAAAQABABAAAAQAAABAAAAQABABAAAAQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBgAgzBLIgBgDIABgEQABAAAAAAQAAAAABgBQAAAAABAAQAAAAABAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAAAAAQABABAAAAQAAABAAAAQABABAAAAQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBgAj4BLIgBgDIABgEQABAAAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAAAIABAEIgBADQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBgAoSBLQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAAAIABAEIgBADQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBgAPpBMIAAhAIgQAFIAAgFIATgIIACAAIAABIgAN0BMIAAgRIgdAAIAAgFIAegxIAEAAIAAAxIAJAAIAAAFIgJAAIAAARgANdA2IAXAAIAAgjIgBAAgAMVBMIAAhAIgPAFIAAgFIATgIIACAAIAABIgAKJBMIAZhCIgiAAIAAgFIAnAAIAAAFIgYBCgAJxBMIAAgRIgcAAIAAgFIAegxIAEAAIAAAxIAJAAIAAAFIgJAAIAAARgAJaA2IAXAAIAAgjIAAAAgAI0BMIAYhCIghAAIAAgFIAnAAIAAAFIgYBCgAIJBMIAZhCIgiAAIAAgFIAnAAIAAAFIgYBCgAHXBMIAAgEIAYghIAFgJQACgDAAgGQAAgFgDgEQgDgDgGAAQgHAAgDAEQgDADAAAKIAAABIgGAAIAAgBQAAgMAFgFQAGgFAIgBQAIABAFAEQAFAFAAAHQAAAGgCAEQgCAGgFAGIgWAeIAgAAIAAAEgAG+BMIAAhAIgQAFIAAgFIATgIIACAAIAABIgAGRBMIAAhAIgPAFIAAgFIATgIIACAAIAABIgAFcBMIAAgiIgdAAIAAAiIgGAAIAAhHIAGAAIAAAgIAdAAIAAggIAFAAIAABHgAEPBMIAAhHIARAAQAJAAAFAGQAFAFAAALQAAAKgFAFQgEAFgKAAIgMAAIAAAdgAEUAqIAMAAQAHABADgFQADgEAAgHQAAgIgDgFQgDgDgHAAIgMAAgADpBMIAAhHIAgAAIAAAGIgbAAIAABBgAB5BMIAAgRIgdAAIAAgFIAegxIAEAAIAAAxIAJAAIAAAFIgJAAIAAARgABiA2IAXAAIAAgjIgBAAgABFBMIAAhAIgPAFIAAgFIATgIIACAAIAABIgAAJBMIAAgRIgbAAIAAgFIAdgxIAEAAIAAAxIAJAAIAAAFIgJAAIAAARgAgNA2IAWAAIAAgjIAAAAgAjOBMIAAgRIgdAAIAAgFIAegxIAEAAIAAAxIAJAAIAAAFIgJAAIAAARgAjlA2IAXAAIAAgjIgBAAgAkSBMIAAgvIgPAAIAAgGIAjAAIAAAGIgPAAIAAAvgAl0BMIgGgTIgYAAIgGATIgFAAIAThHIAIAAIATBHgAmHANIgCAFIgIAhIAWAAIgLgpIgBAAgAm9BMIAZhCIgiAAIAAgFIAoAAIAAAFIgZBCgAp3BMIAAgTIgLAAIAAgBIgMAUIgGAAIALgVQgDgBgDgDQgEgFAAgGQAAgHAFgFQAFgFAJAAIAOAAIAAA1gAqKAgQgDADAAAFQAAAFADADQADADAGAAIAKAAIAAgWIgJAAQgHAAgDADgArCBMIgQgYIgFAAIAAAYIgFAAIAAg1IAFAAIAAAYIAGAAIAOgYIAGAAIgQAaIARAbgAsrBMIAAg1IAPAAQAIAAAEAFQAFACAAAIQAAAEgDADQgCADgEABIAAAAQAGABACAEQADACAAAGQAAAHgFAEQgFADgHAAgAsmBIIAMAAQAGAAADgEQADgCAAgEQAAgFgEgCQgDgDgFAAIgMAAgAsmAvIAKAAQAGAAADgCQADgCAAgFQAAgEgDgDQgEgDgFABIgKAAgAtlBMIAAgYIgWAAIAAAYIgGAAIAAg1IAGAAIAAAYIAWAAIAAgYIAGAAIAAA1gAvwBMIAAgsIgCADIgUApIgGAAIAAg1IAFAAIAAAtIAAAAIAWgtIAHAAIAAA1gAxTBMIAAhBIgSAAIAAgGIAqAAIAAAGIgSAAIAABBgAQ/BDIAAgVIgTAAIAAgGIATAAIAAgUIAFAAIAAAUIATAAIAAAGIgTAAIAAAVgAAWAwIAAgGIAbAAIAAAGgAMGgCIgCAAIAAgFIACABIACAAQAEAAACgDQADgEACgKIgQg1IAGAAIAMAvIABAAIABgFIALgqIAGAAIgRA4QgDALgEAEQgDADgEAAgAnFgJIAAgOIglAAIAAAOIgFAAIAAgSIAFAAQABgDABgEIADgqIAfAAIAAAxIAGAAIAAASgAnigiIgDAHIAZAAIAAgrIgUAAgALhgPIACgFIABgFIAAgJIAGAAIAAAJQAAAEgCADIgEAGgAFugPIACgFIABgFIAAgJIAGAAIAAAJQAAAEgBADIgEAGgAJIgdQgFgIAAgLIAAgCQAAgLAFgIQAFgIAKAAQAHAAAFAGQAEAFAAAHIAAABIgFAAIAAgBQAAgFgDgEQgCgDgGAAQgIAAgDAFQgDAHAAAIIAAADQAAAIADAHQADAGAHABQAGAAADgEQADgFAAgFIAAAAIAFAAIAAAAQAAAIgEAGQgFAFgIAAQgIAAgGgIgAIegdQgFgHAAgMIAAgCQAAgMAFgHQAFgIAJAAQAKAAAFAIQAFAHAAAMIAAACQAAAMgFAHQgFAIgKAAQgIAAgGgIgAIihCQgEAHAAAIIAAADQAAAIAEAHQAEAGAGABQAHgBAEgGQADgFAAgKIAAgDQAAgJgDgGQgEgFgHAAQgGAAgEAFgACngfQgGgIAAgSIAAgDQAAgRAGgJQAHgKAKAAQAKAAAGAKQAHAIAAASIAAADQAAASgHAIQgGAKgKAAQgKAAgHgKgACrhTQgFAIAAAPIAAAEQAAAPAFAHQAFAIAIAAQAIAAAFgIQAEgHAAgPIAAgEQAAgPgEgIQgFgHgIAAQgIAAgFAHgAhigfQgGgIAAgSIAAgDQAAgSAGgIQAHgKAKAAQAKAAAHAKQAGAJAAARIAAADQAAASgGAIQgHAKgKAAQgKAAgHgKgAhehTQgEAIAAAPIAAAEQAAAPAEAHQAFAIAIAAQAIAAAFgIQAEgHAAgPIAAgEQAAgPgEgIQgFgHgIAAQgIAAgFAHgAiWgfQgGgIAAgSIAAgDQAAgRAGgJQAHgKAKAAQAKAAAGAKQAHAIAAASIAAADQAAASgHAIQgGAKgKAAQgKAAgHgKgAiShTQgFAIAAAPIAAAEQAAAPAFAHQAEAIAJAAQAIAAAEgIQAFgHAAgPIAAgEQAAgPgFgIQgEgHgIAAQgJAAgEAHgAjKgfQgHgIAAgSIAAgDQAAgRAGgJQAHgKAKAAQAKAAAHAKQAGAJAAARIAAADQAAASgGAIQgHAKgKAAQgKAAgGgKgAjHhTQgEAIAAAPIAAAEQAAAPAEAHQAGAIAHAAQAJAAAEgIQAFgHAAgPIAAgEQAAgPgFgIQgEgHgJAAQgHAAgGAHgAltgdQgGgHAAgMIAAgCQAAgLAFgIQAFgIAJAAQAIABAFAGQAEAHAAAMIAAADIgeAAIAAAAQAAAKADAFQAEAGAHABQAEAAADgCIAFgFIAEADIgBACIADABQAEAAAAgFIACgLIABghIAfAAIAAA1IgGAAIAAgvIgTAAIgCAcQAAAJgCAGQgCAFgHAAIgCAAIgCgBIAAgEIgEADQgEADgGAAQgKAAgEgIgAlqhCQgDAFAAAIIAZAAIAAAAQAAgHgDgHQgDgEgHAAQgFAAgEAFgAoRgdQgFgGAAgNIAAgCQAAgNAFgGQAFgIAJAAQAJAAAFAIQAGAGAAANIAAACQAAANgGAGQgFAIgJAAQgJAAgFgIgAoNhCQgEAGAAAJIAAADQAAAKAEAFQAEAGAGABQAHgBAEgGQADgFAAgKIAAgDQAAgJgDgGQgEgFgHAAQgGAAgEAFgArlgdQgFgGAAgNIAAgCQAAgNAFgGQAFgIAJAAQAIABAFAGQAEAHAAAMIAAADIgeAAIAAAAQAAAKADAFQAEAGAHABQAFAAACgCIAFgFIAEADQgCAEgEACQgEADgGAAQgJAAgGgIgArhhCQgDAFAAAIIAZAAIAAAAQAAgIgDgGQgCgEgIAAQgGAAgDAFgAwygdQgFgIAAgLIAAgCQAAgLAFgIQAFgIAIAAQAJABAEAGQAFAHAAAMIAAADIgfAAIAAAAQAAAKAEAFQAEAGAHABQAEAAADgCIAFgFIADADQgBAEgFACQgDADgGAAQgKAAgFgIgAwuhCQgDAFgBAIIAZAAIAAAAQAAgHgCgHQgDgEgHAAQgFAAgEAFgAK5gZQgDgFAAgHQAAgIAEgFQAGgDAHAAIALAAIAAgGQAAgGgCgDQgDgEgFAAQgFAAgDAEQgCADAAAEIAAABIgFAAIAAgBQAAgHAEgEQAEgEAHgBQAIAAAEAFQAEAEAAAJIAAAeIABAFIAAABIgFAAIgBgDIgBgEIgFAGQgEADgFgBQgHAAgEgDgAK+guQgDADAAAFQAAAHACABQADAEAFAAQAEAAAFgEQAEgDAAgGIAAgKIgKAAQgGAAgEADgAB6gWIAAgLIgBAAQgMABgHgIQgHgHAAgMQAAgMAHgHQAHgHAMAAIABAAIAAgKIAGAAIAAAKIABAAQANAAAGAHQAHAHAAAMQAAAMgHAHQgHAIgMgBIgBAAIAAALgACAgmIABAAQAKABAFgGQAFgGAAgKQAAgKgFgGQgFgFgKAAIgBAAgABqhLQgFAHAAAJQAAAJAFAHQAGAGAKgBIAAAAIAAgqIAAAAQgKAAgGAFgAj1gXIgBgDIABgEQAAAAABgBQAAAAABAAQAAAAAAAAQABgBAAAAQABAAAAABQABAAAAAAQABAAAAAAQAAABABAAIABAEIgBADQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBgBAAAAgAm7gZQgDgFAAgHQAAgIAEgFQAGgDAHAAIALAAIAAgGQAAgGgCgDQgDgEgFAAQgFAAgDAEQgCADAAAEIAAABIgFAAIAAgBQAAgGAEgFQAEgEAHgBQAIAAAEAFQAEAEAAAJIAAAZIABAKIAAABIgFAAIgBgDIgBgEIgFAGQgEADgFgBQgGAAgFgDgAm2guQgDADAAAFQAAAHADABQACAEAFAAQAEAAAFgEQAEgDAAgGIAAgKIgKAAQgGAAgEADgApxgZQgEgGAAgGQAAgIAFgFQAFgDAHAAIALAAIAAgGQAAgGgCgDQgCgEgGAAQgEAAgEAEQgCACAAAFIAAABIgFAAIAAgBQAAgGAEgFQAEgEAIgBQAHAAAEAFQAEAEAAAJIAAAZIABAKIAAABIgFAAIgCgHQgBADgEADQgEADgFgBQgGAAgEgDgApsguQgEADAAAFQAAAGADACQACAEAFAAQAEAAAFgEQAEgEAAgFIAAgKIgKAAQgGAAgDADgAtggZQgEgGAAgGQAAgIAFgFQAFgDAIAAIALAAIAAgGQAAgGgCgDQgDgEgFAAQgFAAgDAEQgCACAAAFIAAABIgGAAIAAgBQAAgGAEgFQAFgEAHgBQAIAAADAFQAEAEAAAJIAAAZIABAFIABAFIAAABIgFAAIgCgHQgBADgEADQgEADgGgBQgGAAgEgDgAtbguQgDADAAAFQAAAGACACQADAEAFAAQAEAAAFgEQAEgEAAgFIAAgKIgKAAQgHAAgDADgAu/gZQgEgGAAgGQAAgIAFgFQAFgDAIAAIALAAIAAgGQAAgGgCgDQgDgEgFAAQgFAAgDAEQgCADAAAEIAAABIgGAAIAAgBQAAgHAFgEQAEgEAHgBQAIAAADAFQAEAEAAAJIAAAZIABAFIABAFIAAABIgFAAIgCgHQgBADgEADQgEADgGgBQgGAAgEgDgAu6guQgDADAAAFQAAAGACACQADAEAFAAQAEAAAFgEQAEgEAAgFIAAgKIgKAAQgHAAgDADgANZgYQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAAAIABAEIgBADQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBgAMngWIgCgBIAAgFIAEABQADAAABgFQACgDAAgIIABghIAeAAIAAA1IgFAAIAAgvIgUAAIgBAcQAAAKgDAFQgCAFgGAAgAG3gYQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAAAIABAEIgBADQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQgBAAAAgBgAA5gWIgCgBIAAgFIAFABQACAAADgDQACgDADgIIgTg1IAGAAIAOAoIACAGIAAAAIABgDIAOgrIAGAAIgTA1QgEALgDAEQgCAEgGAAgAqjgWIgCgBIgCAAIgQgYIgFAAIAAAYIgFAAIAAg1IAFAAIAAAYIAGAAIAOgYIAGAAIgQAaIAOAWIADABQADAAABgFIACgLIABghIAeAAIAAA1IgFAAIAAgvIgUAAIgBAcQAAAKgDAFQgCAFgGAAgAs3gYIgBgDIABgEQAAAAABAAQAAAAAAgBQABAAAAAAQABAAAAAAQABAAABAAQAAAAABAAQAAABAAAAQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAgBgAvxgWIgCgBIgBAAIgQgYIgFAAIAAAYIgGAAIAAg1IAGAAIAAAYIAFAAIAPgYIAGAAIgQAaIANAWIADABQADAAACgFQABgDAAgIIACghIAeAAIAAA1IgGAAIAAgvIgTAAIgBAcQgBAKgCAFQgCAFgGAAgAKPgXIAAg1IAQAAQAHAAAFAFQAEACAAAIQAAAEgCADQgDADgDABIAAAAQAFABADAEQACADAAAEQAAAIgEAEQgFADgIAAgAKUgbIAMAAQAGgBADgDQADgBAAgGQAAgEgDgCQgEgDgFAAIgMAAgAKUg0IALAAQAGAAACgCQADgDAAgEQAAgFgDgCQgDgDgFABIgLAAgAKGgXIgPgYIgFAAIAAAYIgGAAIAAg1IAGAAIAAAYIAFAAIAOgYIAHAAIgQAaIARAbgAIMgXIAAg5IAAgFIAAAAIgSA+IgGAAIgPg2IgCgDIAAgFIgBAAIAAAFIABADIAAA2IgGAAIAAhHIAIAAIASBBIAThBIAHAAIAABHgAGWgXIAAg1IAbAAIAAAGIgVAAIAAAvgAExgXIAAg5IABgFIgBAAIgRA+IgGAAIgQg2IgBgDIgBgFIAAAAIAAAFIAAADIAAA2IgFAAIAAhHIAHAAIAQA5IADAIIAShBIAIAAIAABHgADYgXIAAhHIARAAQAJAAAFAGQAFAFAAALQAAAKgFAFQgEAFgKABIgMAAIAAAcgADdg5IAMAAQAHABADgFQADgEAAgHQAAgIgDgFQgDgDgHAAIgMAAgAAOgXIAAhHIARAAQAJAAAGAGQAEAFAAALQAAAKgEAFQgFAFgKABIgLAAIAAAcgAAUg5IALAAQAHABADgFQAEgEAAgHQAAgIgEgFQgDgDgHAAIgLAAgAkegXIAAg1IAGAAIAAAUIAJAAQAJAAAFAFQAEAEAAAHQAAAIgEAFQgFAEgJAAgAkYgbIAJAAQAHAAADgEQADgEAAgFQAAgEgDgEQgCgDgIAAIgJAAgAmJgXIAAgvIgPAAIAAgGIAkAAIAAAGIgPAAIAAAvgAoigXIAAgtIgBAAIgNAtIgHAAIgNgtIgBAAIAAAtIgFAAIAAg1IAIAAIAOAvIABAAIABgEIANgrIAIAAIAAA1gAsRgXIAAhHIARAAQAKAAAEAGQAFAFAAALQAAAKgFAFQgEAFgKABIgLAAIAAAcgAsLg5IALAAQAHABADgFQAEgEAAgHQAAgIgEgFQgDgDgHAAIgLAAgAtwgXIAAgqIABgDIgBAAIgOAtIgGAAIgOgtIAAAAIAAADIAAAEIAAAmIgFAAIAAg1IAIAAIAOAvIABAAIAOgvIAIAAIAAA1gAxegXIAAhHIARAAQAJAAAFAGQAFAFAAALQAAAKgFAFQgFAFgJABIgMAAIAAAcgAxZg5IAMAAQAHABADgFQADgEAAgHQAAgIgDgFQgDgDgHAAIgMAAgAFUgbIANgWIgNgWIAFAAIAOAUIAAADIgOAVgAE/gbIAMgWIgMgWIAFAAIANAUIAAADIgNAVgAABgbIgMgWIAAgCIANgUIAEAAIgLAVIALAXgAgTgbIgOgWIAAgCIAOgUIAFAAIgNAVIANAXgAj1hEIgBgDQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAAAgBQAAAAABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABAAIABAEIgBADIgEABg");
	this.shape.setTransform(112.625,9.65);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Group, new cjs.Rectangle(0,0,225.3,19.3), null);


(lib.Group_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AnpBiIAAgTQgKAAgGgIQgGgHAAgMIAAgCQAAgMAGgHQAGgHAKgBIAAgVIAGAAIAAAVQAKABAFAHQAHAHAAAMIAAACQAAAMgHAHQgGAIgJAAIAAATgAnjBKQAHgBAFgFQAEgGAAgKIAAgCQAAgKgFgFQgFgGgGAAgAn1AjQgFAFAAAKIAAACQAAAKAFAGQAFAFAHABIAAgtQgHAAgFAGgAkHBWIADgFIAAgPIAHAAIAAAJQAAADgCAEQgCAFgCABgApPBWIADgFIAAgPIAHAAIAAAJQAAAEgCADIgEAGgAJ0BKQgFgFAAgKQAAgHADgEQADgFAFgCIAAAAQgDgCgEgEQgCgEAAgHQAAgJAFgFQAEgFAIAAQAHAAAGAFQAFAFAAAJQAAAGgDAFQgDAEgEACIAAAAQAFACAEAFQADAEAAAHQAAAJgGAGQgFAFgJAAQgJAAgFgFgAJ4AwQgEADAAAHQAAAIAEAEQAEAEAGAAQAGAAAEgEQAEgFAAgHQAAgGgEgEQgEgEgGAAQgGAAgEAEgAJ5AOQgDAEAAAGQAAAGADAFQAEAEAFAAQAFAAAEgEQADgFAAgGQAAgGgDgEQgDgEgGAAQgFAAgEAEgAH3BJQgFgFAAgLIAAgeQAAgLAFgFQAEgGAJAAQAJAAAFAGQAEAFAAALIAAAeQAAAKgEAGQgEAGgKAAQgJAAgEgGgAH7APQgDAEAAAIIAAAeQAAAIADAEQADAFAGAAQAHAAADgFQADgEAAgIIAAgeQAAgIgDgEQgDgFgHAAQgGAAgDAFgAGhBKQgGgFAAgKQAAgHADgEQAEgFAFgCIAAAAQgDgCgEgEQgDgEAAgHQAAgJAFgFQAFgFAIAAQAHAAAFAFQAFAFAAAJQAAAGgCAFQgEAEgDACIAAAAQAFACADAFQADAEAAAHQAAAJgFAGQgGAFgIAAQgJAAgFgFgAGkAwQgDADAAAHQAAAIADAEQAEAEAHAAQAGAAAEgEQAEgFAAgHQAAgGgEgEQgEgEgGAAQgHAAgEAEgAGmAOQgDAEAAAGQAAAGADAFQAEAEAFAAQAFAAAEgEQADgFAAgGQAAgGgDgEQgEgEgFAAQgGAAgDAEgAFJBKQgFgFAAgKIAAgBIAFAAIAAABQAAAHAEAEQADAEAGAAQAGAAAEgEQAEgFAAgHQAAgHgFgEQgEgEgGAAIgGAAIAAgFIAFAAQAGAAAEgEQADgDAAgHQAAgGgDgEQgCgEgGAAQgFAAgDAEQgDAEAAAFIAAACIgGAAIAAgCQAAgIAFgFQAFgFAHAAQAIAAAEAFQAFAFAAAJQAAAEgCAFQgEAFgEACQAFACAEAEQADAEAAAJQAAAKgFAFQgFAFgJAAQgIAAgFgFgAEfBJQgFgGAAgKIAAgeQAAgLAFgFQAEgGAJAAQAJAAAFAGQAFAFAAALIAAAeQAAALgFAFQgEAGgKAAQgJAAgEgGgAEjAPQgDAEAAAIIAAAeQAAAIADAEQADAFAGAAQAHAAADgFQADgEAAgIIAAgeQAAgIgDgEQgDgFgHAAQgGAAgDAFgAjaBGQgGgJAAgSIAAgDQAAgRAGgJQAHgJAKAAQAKAAAGAJQAHAJAAARIAAADQAAASgHAJQgGAJgKAAQgKAAgHgJgAjWASQgFAHAAAPIAAAEQAAAPAFAHQAEAIAJAAQAIAAAEgIQAFgHAAgPIAAgEQAAgPgFgHQgEgIgIAAQgJAAgEAIgAokBIQgGgIAAgMIAAgCQAAgLAGgIQAFgIAJAAQAJAAAFAIQAGAIAAALIAAACQAAAMgGAIQgFAHgJAAQgJAAgFgHgAohAjQgDAFAAAKIAAACQAAAKADAGQAEAGAHAAQAHAAADgGQAEgGAAgKIAAgCQAAgKgEgFQgDgGgHAAQgHAAgEAGgArWBKQgFgFAAgHIAAgBIAGAAIAAABQAAAFADAEQADADAFAAQAHAAAEgGQADgFAAgKIgRAAIAAgFIARAAQAAgJgDgFQgEgFgHAAQgFAAgDADQgDAEAAAFIAAAAIgFAAIAAAAQAAgIAEgFQAGgFAGAAQAKAAAFAIQAFAHAAAMIAAACQAAAMgFAIQgGAHgJAAQgIAAgEgFgALLBNQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQAAgBABAAQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABIABADIgBAEQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAgAIgBNQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAgBAAAAQABAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAAAABABIABADIgBAEQgBAAAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAAAgAnFBNQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAgBAAAAQABAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAAAAAABQABAAAAABQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAAAgAqLBNIgBgEIABgDQABgBAAAAQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABIABADIgBAEQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAgBAAgAJWBNIAAhAIgQAFIAAgFIATgIIACAAIAABIgAHhBNIAAgRIgdAAIAAgFIAegxIAEAAIAAAxIAJAAIAAAFIgJAAIAAARgAHKA3IAXAAIAAgjIgBAAgAGCBNIAAhAIgPAFIAAgFIATgIIACAAIAABIgAD2BNIAZhCIgiAAIAAgFIAnAAIAAAFIgYBCgADeBNIAAgRIgcAAIAAgFIAegxIAEAAIAAAxIAJAAIAAAFIgJAAIAAARgADHA3IAXAAIAAgjIAAAAgAChBNIAYhCIghAAIAAgFIAnAAIAAAFIgYBCgAB2BNIAZhCIgiAAIAAgFIAoAAIAAAFIgZBCgABEBNIAAgEIAYghIAFgIQACgEAAgGQAAgFgDgEQgDgDgGAAQgGAAgEAEQgDAEAAAJIAAABIgGAAIAAgBQAAgMAFgFQAGgFAIAAQAIAAAFAEQAFAFAAAIQAAAFgCAFIgHALIgWAeIAgAAIAAAEgAArBNIAAhAIgQAFIAAgFIATgIIACAAIAABIgAgBBNIAAhAIgPAFIAAgFIASgIIACAAIAABIgAg2BNIAAgiIgdAAIAAAiIgGAAIAAhHIAGAAIAAAgIAdAAIAAggIAGAAIAABHgAiDBNIAAhHIARAAQAJAAAFAGQAFAFAAALQAAAKgFAFQgFAGgJAAIgMAAIAAAcgAh+AsIAMAAQAHAAADgFQADgEAAgHQAAgIgDgEQgDgEgHAAIgMAAgAipBNIAAhHIAgAAIAAAGIgbAAIAABBgAkZBNIAAgRIgdAAIAAgFIAegxIAEAAIAAAxIAJAAIAAAFIgJAAIAAARgAkwA3IAXAAIAAgjIgBAAgAlNBNIAAhAIgPAFIAAgFIATgIIACAAIAABIgAmJBNIAAgRIgcAAIAAgFIAegxIAEAAIAAAxIAJAAIAAAFIgJAAIAAARgAmgA3IAXAAIAAgjIAAAAgAphBNIAAgRIgcAAIAAgFIAdgxIAEAAIAAAxIAJAAIAAAFIgJAAIAAARgAp4A3IAXAAIAAgjIgBAAgAqlBNIAAgvIgPAAIAAgFIAjAAIAAAFIgPAAIAAAvgAKsBEIAAgVIgTAAIAAgFIATAAIAAgVIAFAAIAAAVIATAAIAAAFIgTAAIAAAVgAl8AxIAAgFIAbAAIAAAFgAH4AAIgCgBIAAgFIACABIADAAQADAAACgDQADgEACgJIAAgBIgQg0IAGAAIALApIABAFIABAAIABgFIALgpIAGAAIgRA4QgEALgDADQgDAEgEAAgAMCgBIAAgTQgKAAgGgIQgGgHAAgMIAAgCQAAgMAGgHQAGgHAKgBIAAgVIAFAAIAAAVQAKABAGAHQAHAHAAAMIAAACQAAAMgHAHQgGAIgKAAIAAATgAMHgZQAIgBAEgFQAFgGAAgKIAAgCQAAgKgFgFQgFgGgHAAgAL2hAQgFAGAAAJIAAACQAAAKAFAGQAFAFAHABIAAgtQgGAAgGAGgAKYgBIAAhJIAFAAIAAAGQADgDADgCQAEgCAFAAQAIAAAEAHQAFAIAAALIAAACQAAAMgFAHQgEAHgIAAQgFAAgEgBQgDgBgCgEIAAAagAKihEIgEAGIAAAdQAAACAEADQADACAFAAQAHAAADgGQADgHAAgIIAAgCQAAgIgDgHQgEgGgGAAQgFAAgDACgASzgIIAAgOIglAAIAAAOIgFAAIAAgTIAFAAQACgDAAgDIADgpIAfAAIAAAvIAGAAIAAATgASWghIgDAGIAZAAIAAgqIgUAAgArTgIIAAgOIglAAIAAAOIgFAAIAAgTIAFAAIACgGIACgOIABgbIAfAAIAAAvIAHAAIAAATgArwghIgCAGIAYAAIAAgqIgUAAgAVkgNIACgFIABgGIAAgJIAGAAIAAAJQAAAEgBADIgEAGgARngNIACgFIABgGIAAgJIAGAAIAAAJQAAAEgBADQgCAFgCABgAHTgNIACgFIABgGIAAgJIAGAAIAAAJQAAAEgCADQgBAFgDABgABggNIACgFIABgGIAAgJIAGAAIAAAJQAAAEgBADQgCAFgCABgATmgZQgGgGAAgIIAAgBIAGAAIAAAAQAAAHAEAEQADAEAGAAQAHAAADgFQAEgFAAgJQAAgIgEgGQgEgEgFAAQgEAAgEADQgDABgCADIgEgCIADgkIAdAAIAAAGIgYAAIgDAaIAFgEIAIgCQAHAAAFAGQAFAFAAALQAAANgFAGQgFAGgJAAQgIAAgFgFgAPQgbQgFgHAAgNIAAgCQAAgMAFgHQAFgIAJAAQAIAAAEAGQAEAFAAAIIAAAAIgFAAIAAAAQAAgFgDgFQgCgDgGAAQgHAAgDAGQgEAFAAAKIAAACQAAAKAEAGQADAGAHAAQAGAAACgEQADgEAAgFIAAgBIAFAAIAAABQAAAHgEAGQgEAFgIAAQgJAAgFgHgAN8gbQgFgHAAgNIAAgCQAAgMAFgHQAFgIAJAAQAJAAAGAIQAFAHAAAMIAAACQAAANgFAHQgGAHgJAAQgJAAgFgHgAOAhAQgEAFAAAKIAAACQAAAKAEAGQAEAGAGAAQAHAAAEgGQADgGAAgKIAAgCQAAgKgDgFQgEgGgHAAQgGAAgEAGgAMmgbQgFgIAAgMIAAgCQAAgLAFgIQAGgIAJAAQAJAAAFAIQAFAIAAALIAAACQAAAMgFAIQgFAHgJAAQgKAAgFgHgAMqhAQgDAFAAAKIAAACQAAAKADAGQAEAGAHAAQAHAAADgGQAEgHAAgJIAAgCQAAgIgEgHQgDgGgHAAQgHAAgEAGgAE6gbQgFgJAAgLIAAgCQAAgLAFgIQAGgIAJAAQAHAAAFAGQAEAFAAAIIAAAAIgFAAIAAAAQAAgFgDgFQgDgDgFAAQgIAAgDAGQgDAHAAAIIAAACQAAAJADAHQADAGAHAAQAHAAACgEQADgEAAgFIAAgBIAFAAIAAABQAAAIgEAFQgFAFgIAAQgJAAgFgHgAEQgbQgFgIAAgMIAAgCQAAgLAFgIQAGgIAIAAQAKAAAFAIQAFAIAAALIAAACQAAAMgFAIQgFAHgKAAQgJAAgFgHgAEUhAQgEAHAAAIIAAACQAAAJAEAHQAEAGAGAAQAHAAAEgGQADgGAAgKIAAgCQAAgKgDgFQgEgGgHAAQgGAAgEAGgAhmgdQgGgJAAgSIAAgDQAAgRAGgJQAHgJAKAAQAKAAAHAJQAGAJAAARIAAADQAAASgGAJQgHAJgKAAQgLAAgGgJgAhihRQgFAHAAAPIAAAEQAAAPAFAHQAFAIAIAAQAIAAAFgIQAEgHAAgPIAAgEQAAgPgEgHQgFgIgIAAQgIAAgFAIgAlwgdQgGgKAAgRIAAgDQAAgQAGgKQAHgJAKAAQAKAAAHAJQAGAJAAARIAAADQAAASgGAJQgGAJgLAAQgLAAgGgJgAlshRQgEAHAAAPIAAAEQAAAPAEAHQAFAIAIAAQAIAAAFgIQAEgHAAgPIAAgEQAAgPgEgHQgFgIgIAAQgIAAgFAIgAmkgdQgGgJAAgSIAAgDQAAgRAGgJQAHgJAKAAQAKAAAGAJQAHAJAAARIAAADQAAASgHAJQgGAJgKAAQgKAAgHgJgAmghRQgFAHAAAPIAAAEQAAAPAFAHQAEAIAJAAQAIAAAEgIQAFgHAAgPIAAgEQAAgPgFgHQgEgIgIAAQgJAAgEAIgAnYgdQgHgJAAgSIAAgDQAAgRAHgJQAGgJAKAAQAKAAAHAJQAGAJAAARIAAADQAAASgGAJQgGAJgLAAQgKAAgGgJgAnUhRQgFAHAAAPIAAAEQAAAPAFAHQAEAIAIAAQAJAAAEgIQAFgHAAgPIAAgEQAAgPgFgHQgEgIgJAAQgIAAgEAIgAoDgWIgBgDIABgEQABAAAAAAQAAgBABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAIABAEIgBADQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAgAp7gbQgGgIAAgMIAAgCQAAgLAFgIQAGgIAIAAQAIAAAFAHQAEAHAAANIAAACIgeAAQAAAKADAGQAEAGAHAAQAEAAADgCIAFgFIAEADIgBADIADAAQADAAACgEIABgMIABggIAfAAIAAA0IgGAAIAAgvIgTAAIgCAcQAAAJgCAGQgCAFgHAAIgCAAIgCgBIAAgEIgEADQgDADgHAAQgKAAgEgHgApfgaIABAAIgBgBgAp4hAQgDAFAAAHIAZAAIAAAAQAAgJgDgEQgDgFgHAAQgFAAgEAGgAsfgbQgFgHAAgNIAAgCQAAgMAFgHQAFgIAJAAQAJAAAGAIQAFAHAAAMIAAACQAAANgFAHQgGAHgJAAQgJAAgFgHgAsbhAQgEAFAAAKIAAACQAAAKAEAGQAEAGAGAAQAHAAAEgGQADgGAAgKIAAgCQAAgKgDgFQgEgGgHAAQgGAAgEAGgAvzgbQgFgHAAgNIAAgCQAAgMAFgHQAGgIAIAAQAIAAAFAHQAEAHAAANIAAACIgeAAQAAAKADAGQAEAGAHAAQAEAAADgCIAFgFIAEADQgBADgFADQgDADgHAAQgKAAgFgHgAvvhAQgDAFAAAHIAZAAIAAAAQAAgIgDgFQgCgFgIAAQgGAAgDAGgA1AgbQgFgIAAgMIAAgCQAAgLAFgIQAFgIAIAAQAJAAAEAHQAFAHAAANIAAACIgfAAQAAAKAEAGQAEAGAHAAQAEAAADgCIAFgFIAEADQgDAEgEACQgDADgGAAQgLAAgEgHgA08hAQgDAFgBAHIAZAAIAAAAQAAgHgCgGQgDgFgHAAQgFAAgEAGgAS+gWIgBgEIABgDQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAAAABABIABADIgBAEQgBAAAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAgAQXgYQgEgFAAgHQAAgIAFgEQAFgFAIAAIALAAIAAgFQAAgGgCgDQgDgEgFAAQgGAAgCAEQgCADAAAEIgGAAQAAgGAFgFQAEgFAHAAQAIAAADAFQAEAFAAAIIAAAZIABAGIABAFIAAAAIgFAAIgCgGQgCADgDACQgDACgHAAQgGAAgEgDgAQcgtQgDADAAAGQAAAEACAEQADADAFAAQAEAAAFgEQAEgEAAgEIAAgLIgKAAQgGAAgEADgAJLgWQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQAAgBABAAQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABIABADIgBAEQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAgAIZgVIgCgBIAAgFIAEABQADAAABgEQACgEAAgIIABggIAeAAIAAA0IgFAAIAAgvIgUAAIgBAcQAAAKgDAFQgCAFgGAAgAGrgYQgDgEAAgIQAAgIAEgEQAGgFAHAAIALAAIAAgFQAAgFgCgEQgDgEgFAAQgGAAgCAEQgCADAAAEIgFAAQAAgGAEgFQAEgFAHAAQAHAAAFAFQAEAFAAAIIAAAfIABAFIAAAAIgFAAIgBgDIgBgDQgCADgDACQgDACgGAAQgHAAgEgDgAGwgtQgDADAAAGQAAAFADADQACADAFAAQAEAAAFgEQAEgDAAgFIAAgLIgKAAQgFAAgFADgACpgWQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABgBAAAAQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABIABADIgBAEQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAgBAAgAiTgVIAAgKIgBAAQgMAAgHgHQgHgHAAgNQAAgMAHgHQAHgHAMAAIABAAIAAgKIAGAAIAAAKIABAAQANAAAGAHQAHAHAAAMQAAANgHAHQgHAHgMAAIgBAAIAAAKgAiNgkIABAAQAKAAAFgGQAFgFAAgLQAAgKgFgFQgFgGgKAAIgBAAgAijhJQgFAFAAAKQAAAKAFAGQAGAGAKAAIAAAAIAAgrIAAAAQgKAAgGAGgAjUgVIgCgBIAAgFIAFABQADAAACgDQACgCADgJIgTg1IAGAAIAOAoIACAHIAAAAIABgDIAOgsIAGAAIgTA1QgDALgEAEQgDAEgFAAgArJgYQgDgEAAgIQAAgIAFgEQAEgFAIAAIALAAIAAgFQAAgFgCgEQgDgEgFAAQgGAAgCAEQgCACAAAFIgFAAQAAgGAEgFQAEgFAHAAQAHAAAFAFQAEAFAAAIIAAAZIABALIAAAAIgFAAIgBgDIgBgDQgCADgDACQgDACgGAAQgHAAgEgDgArEgtQgDADAAAGQAAAFADADQACADAFAAQAEAAAFgEQAEgDAAgFIAAgLIgKAAQgFAAgFADgAt/gYQgEgFAAgHQAAgIAFgEQAEgFAIAAIALAAIAAgFQAAgGgCgDQgCgEgGAAQgFAAgCAEQgDACAAAFIgFAAQAAgGAEgFQAEgFAIAAQAHAAAEAFQAEAFAAAIIAAAZIAAAGIACAFIAAAAIgGAAIgBgDIgBgDQgCADgDACQgDACgGAAQgHAAgDgDgAt6gtQgEADAAAGQAAAEADAEQACADAFAAQAEAAAFgEQAEgEAAgEIAAgLIgKAAQgGAAgDADgAuxgVIgCgBIgCAAIgPgYIgGAAIAAAYIgFAAIAAg0IAFAAIAAAXIAGAAIAOgXIAGAAIgQAZIAOAXIABAAIACAAQADAAABgEQACgEAAgIIABggIAeAAIAAA0IgFAAIAAgvIgUAAIgBAcQAAAKgDAFQgCAFgGAAgAxFgWQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQAAgBABAAQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAgBQgBAAAAAAgAxugYQgEgFAAgHQAAgHAFgFQAFgFAIAAIALAAIAAgFQAAgGgCgDQgDgEgFAAQgGAAgCAEQgCADAAAEIgGAAQAAgGAFgFQAEgFAHAAQAIAAADAFQAEAFAAAIIAAAZIABAGIABAFIAAAAIgFAAIgCgGQgCADgDACQgDACgHAAQgGAAgEgDgAxpgtQgDAEAAAFQAAAEACAEQADADAFAAQAEAAAFgEQAEgEAAgEIAAgLIgKAAQgGAAgEADgAzNgYQgEgFAAgHQAAgHAFgFQAFgFAIAAIALAAIAAgFQAAgGgCgDQgDgEgFAAQgGAAgCAEQgCADAAAEIgGAAQAAgGAFgFQAEgFAHAAQAIAAADAFQAEAEAAAJIAAAZIABAGIABAFIAAAAIgFAAIgCgGQgCADgDACQgDACgHAAQgGAAgEgDgAzIgtQgDAEAAAFQAAAEACAEQADADAFAAQAEAAAFgEQAEgEAAgEIAAgLIgKAAQgGAAgEADgAz/gVIgCgBIgBAAIgQgYIgFAAIAAAYIgGAAIAAg0IAGAAIAAAXIAFAAIAPgXIAGAAIgQAZIAOAXIAAAAIACAAQADAAACgEQABgEAAgIIACggIAeAAIAAA0IgGAAIAAgvIgTAAIgBAcQgBAKgCAFQgCAFgGAAgAVbgWIgFgTIgZAAIgFATIgGAAIAUhHIAIAAIATBHgAU+guIAXAAIgLgqIgBAAgAUTgWIAYhCIghAAIAAgFIAnAAIAAAFIgYBCgARYgWIAAgTIgLAAIAAAAIgLATIgHAAIAMgVQgEgBgCgCQgEgEAAgIQAAgHAFgFQAFgEAJAAIAOAAIAAA0gARGhCQgDADAAAFQAAAFACADQADAEAHAAIAJAAIAAgXIgIAAQgHAAgDADgAQOgWIgQgYIgFAAIAAAYIgGAAIAAg0IAGAAIAAAXIAFAAIAPgXIAGAAIgQAZIARAbgAOkgWIAAg0IAQAAQAHAAAFADQAEAEAAAHQAAAFgCACQgCADgEABQAFACADADQADADAAAFQAAAHgFAEQgEADgJAAgAOqgbIALAAQAHAAACgCQADgCAAgFQAAgFgDgCQgDgDgGAAIgLAAgAOqgzIAKAAQAGAAACgCQADgCAAgFQAAgEgDgDQgDgCgFAAIgKAAgANrgWIAAgYIgXAAIAAAYIgFAAIAAg0IAFAAIAAAXIAXAAIAAgXIAFAAIAAA0gALggWIAAgsIgWAsIgHAAIAAg0IAGAAIAAApIgBADIABAAIAWgsIAGAAIAAA0gAJ9gWIAAhCIgTAAIAAgFIArAAIAAAFIgTAAIAABCgAGBgWIAAg0IAQAAQAHAAAFADQAEAEAAAHQAAAEgCADQgDAEgDAAQAGACACADQACADAAAFQAAAHgEAEQgEADgJAAgAGGgbIAMAAQAGAAADgCQADgCAAgFQAAgFgDgCQgEgDgFAAIgMAAgAGGgzIALAAQAGAAACgCQADgDAAgEQAAgEgDgDQgDgCgFAAIgLAAgAF4gWIgPgYIgFAAIAAAYIgGAAIAAg0IAGAAIAAAXIAFAAIAOgXIAHAAIgRAZIASAbgAD+gWIAAg5IAAgFIAAAAIgSA+IgGAAIgRg+IgBAAIAAAFIABAEIAAA1IgGAAIAAhHIAIAAIASBBIAThBIAHAAIAABHgACIgWIAAg0IAbAAIAAAFIgVAAIAAAvgAAjgWIAAg5IABgFIgBAAIgRA+IgGAAIgPg1IgBgEIgBgFIAAAAIAAAFIAAAEIAAA1IgFAAIAAhHIAHAAIASBBIAShBIAIAAIAABHgAg1gWIAAhHIARAAQAJAAAFAGQAFAFAAALQAAAKgFAFQgFAGgJAAIgMAAIAAAcgAgwg3IAMAAQAHAAADgFQADgEAAgHQAAgIgDgEQgDgEgHAAIgMAAgAj/gWIAAhHIARAAQAJAAAGAGQAEAFAAALQAAAKgEAFQgGAGgJAAIgLAAIAAAcgAj5g3IALAAQAHAAADgFQAEgEAAgHQAAgIgEgEQgCgEgIAAIgLAAgAosgWIAAg0IAGAAIAAATIAJAAQAKAAAEAEQAEAFAAAIQAAAHgEAFQgFAEgJAAgAomgbIAJAAQAIAAACgDQADgDAAgFQAAgFgDgEQgCgDgIAAIgJAAgAqXgWIAAgvIgPAAIAAgFIAkAAIAAAFIgPAAIAAAvgAswgWIAAgpIAAgEIgBAAIgNAtIgGAAIgOgtIgBAAIAAAtIgFAAIAAg0IAIAAIAOAuIABAAIAOguIAIAAIAAA0gAwfgWIAAhHIARAAQAKAAAEAGQAFAFAAALQAAAKgFAFQgEAGgKAAIgLAAIAAAcgAwZg3IALAAQAHAAADgFQAEgEAAgHQAAgIgEgEQgCgEgIAAIgLAAgAx+gWIAAgpIABgEIgBAAIgBAEIgNApIgGAAIgOgtIAAAAIAAAEIAAADIAAAmIgFAAIAAg0IAIAAIANArIABADIABAAIAOguIAIAAIAAA0gA1sgWIAAhHIARAAQAJAAAFAGQAFAFAAALQAAAKgFAFQgFAGgJAAIgMAAIAAAcgA1ng3IAMAAQAHAAADgFQADgEAAgHQAAgIgDgEQgDgEgHAAIgMAAgABGgaIANgWIgNgWIAFAAIAOAVIAAACIgOAVgAAxgaIAMgWIgMgWIAFAAIANAVIAAACIgNAVgAkMgaIgNgVIAAgDIAOgUIAEAAIgMAWIAMAWgAkhgaIgNgVIAAgDIANgUIAFAAIgNAWIANAWgAoDhDQAAAAAAAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIABgEIADgBIAEABIABAEQAAAAAAABQAAABAAAAQgBABAAAAQAAAAAAAAQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_1.setTransform(138.925,9.775);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Group_1, new cjs.Rectangle(0,0,277.9,19.6), null);


(lib.blur2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F40014").s().p("Eg8UAzPQpOixjxmoQjympCTpWQCOpCHlqTQHlqSLvp/QMLqWO7ogQO6ohPElOQOllCMuhSQMvhSI5CrQJOCyDyGoQDyGpiTJWQiOJBnlKUQnlKSrvJ/QsLKVu7IhQu6IhvFFOQukFCsuBSQkHAajtAAQnyAAmDh0g");
	this.shape.setTransform(-514.25,-172.0386);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.blur2, new cjs.Rectangle(-998.5,-511.5,968.6,679), null);


(lib.blur1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D90012").s().p("Eg7YA05QpqjkkSnfQkRngB3qIQBypyHQq5QHPq4LkqUQL+qqO7ohQO7ohPRk4QOwkuNEgsQNDgtJWDcQJqDkESHfQERHgh3KIQhyJynQK5QnPK4rkKTQr/Kru6IhQu6IhvRE4QuwEutEAsQiNAHiGAAQqVABnyi3g");
	this.shape.setTransform(-118.05,-206.7493);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.blur1, new cjs.Rectangle(-606.4,-563.5,976.7,713.5), null);


(lib.Tween10 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Group_1();
	this.instance.setTransform(5.35,-44.1,1.25,1.25,0,0,0,138.9,9.8);
	this.instance.alpha = 0.6992;

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag4BDIgEgBIgBgCIAAgHIABgDQABgCADgDIA4g2QAFgHACgDQACgHAAgEQAAgLgGgHQgFgGgMgBQgIABgFADQgGADgDAFQgDAFgBAIQAAAAAAABQAAAAgBABQAAAAgBABQAAAAAAAAIgDABIgKAAIgDgBIgBgCQAAgIADgHQAEgJAFgEQAFgHAJgDQAHgDAMgBQAPABAJAFQAKAGAEAIQAEAJAAALQAAAHgCAIQgDAGgGAHQgFAGgIAHIgkAlIA7AAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIAAAIIgBACQgBABAAAAQAAAAAAAAQgBAAAAAAQgBAAAAAAgAhjBDIgDgBIgBgCIAAhqIggAYIgDABIgDgBIgFgHIgBgEIACgDIApgfIADgCIAMAAIADACIABADIAAB8IgBACIgDABgABeA+IgDgCQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAAAAAgBIAAgnIgnAAIgDgBQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAAAAAgBIAAgGQAAAAAAgBQAAAAAAgBQAAAAAAAAQABgBAAAAIADgBIAnAAIAAgmIACgDQAAAAAAgBQAAAAABAAQAAAAABAAQAAgBABAAIAHAAQAAAAAAABQABAAAAAAQABAAAAAAQAAABAAAAIACADIAAAmIAnAAIADABQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAABIAAAGIgBAEIgDABIgnAAIAAAnQAAABgBAAQAAAAAAABQAAAAAAABQgBAAAAAAIgCACg");
	this.shape.setTransform(1277.4396,-45.4125,1.25,1.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168.3,-56.3,1464.3,24.4);


(lib.Symbol22 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_7
	this.instance = new lib.big2();
	this.instance.setTransform(-180,-122,0.6667,0.6667);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer_5
	this.instance_1 = new lib.blur2();
	this.instance_1.setTransform(143.3,229.85,1,1,0,0,0,-224,-176.8);
	this.instance_1.filters = [new cjs.BlurFilter(255, 255, 1), new cjs.BlurFilter(254, 254, 1)];
	this.instance_1.cache(-1000,-513,973,683);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Layer_4
	this.instance_2 = new lib.blur1();
	this.instance_2.setTransform(-364.45,252.1,1,1,0,0,0,-233.5,-161.3);
	this.instance_2.filters = [new cjs.BlurFilter(255, 255, 1), new cjs.BlurFilter(255, 255, 1)];
	this.instance_2.cache(-608,-565,981,718);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol22, new cjs.Rectangle(-993.3,-406.1,1589.1,1238.2), null);


(lib.Символ6copy2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// but
	this.instance = new lib.Tween7("synched",0);
	this.instance.setTransform(165.65,252.6);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(19).to({_off:false},0).to({y:154.6,alpha:1},39,cjs.Ease.cubicOut).to({startPosition:0},6).to({scaleX:0.9,scaleY:0.9,x:165.6,y:154.55},40,cjs.Ease.quadInOut).to({scaleX:1,scaleY:1,x:165.65,y:154.6},40,cjs.Ease.quadInOut).to({scaleX:0.9,scaleY:0.9,x:165.6,y:154.55},40,cjs.Ease.quadInOut).to({scaleX:1,scaleY:1,x:165.65,y:154.6},40,cjs.Ease.quadInOut).to({scaleX:0.9,scaleY:0.9,x:165.6,y:154.55},40,cjs.Ease.quadInOut).to({scaleX:1,scaleY:1,x:165.65,y:154.6},40,cjs.Ease.quadInOut).to({scaleX:0.9,scaleY:0.9,x:165.6,y:154.55},40,cjs.Ease.quadInOut).to({scaleX:1,scaleY:1,x:165.65,y:154.6},40,cjs.Ease.quadInOut).to({scaleX:0.9,scaleY:0.9,x:165.6,y:154.55},40,cjs.Ease.quadInOut).to({scaleX:1,scaleY:1,x:165.65,y:154.6},40,cjs.Ease.quadInOut).wait(16));

	// Layer_5
	this.instance_1 = new lib.Tween8("synched",0);
	this.instance_1.setTransform(165.8,177.15);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({_off:false},0).to({y:79.15,alpha:1},39,cjs.Ease.cubicOut).wait(432));

	// Layer_6
	this.instance_2 = new lib.Tween9("synched",0);
	this.instance_2.setTransform(164.75,140.4);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:42.4,alpha:1},39,cjs.Ease.cubicOut).wait(441));

	// dis
	this.instance_3 = new lib.Tween10("synched",0);
	this.instance_3.setTransform(159.8,250.8);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({alpha:1},39).wait(441));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-11.2,54.9,1467,223.99999999999997);


(lib._main_1500 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// _text_anim
	this.instance = new lib.Символ6copy2("synched",0);
	this.instance.setTransform(-475.7,-101,0.8,0.8,0,0,0,93.3,68.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(480));

	// Layer_7
	this.instance_1 = new lib.Tween11("synched",0);
	this.instance_1.setTransform(10.55,-6);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:0},13).to({_off:true},1).wait(466));

	// trans
	this.instance_2 = new lib.Tween6("synched",0);
	this.instance_2.setTransform(59.1,9);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(459).to({_off:false},0).to({alpha:1},20).wait(1));

	// logo_pd
	this.instance_3 = new lib.logopd("synched",0);
	this.instance_3.setTransform(4.45,-43.2,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({scaleX:1,scaleY:1,x:4.5},39,cjs.Ease.cubicInOut).to({regX:0.1,regY:-0.1,scaleX:1.06,scaleY:1.06,x:4.55},440).wait(1));

	// shadow
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("rgba(51,51,51,0)").ss(0.1,1,1).p("Am+DoIAAnPIN9AAIAAHP");
	this.shape.setTransform(-206.5,-87.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#1E2130","rgba(30,33,48,0)"],[0,1],0,46.2,0,-46.2).s().p("ElmlAHOIAAubMLNLAAAIAAObg");
	this.shape_1.setTransform(-45.05,34.225);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(480));

	// pic
	this.instance_4 = new lib.Symbol22();
	this.instance_4.setTransform(284.4,80.7,1,1,0,0,0,284.4,80.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({regX:284.2,scaleX:1.05,scaleY:1.05,x:284.3,y:80.75},479).wait(1));

	// Layer_2
	this.instance_5 = new lib.Symbol25();
	this.instance_5.setTransform(0,-50,1,0.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(480));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2670.3,-417.6,5458.8,1274.6);


(lib._main_320 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_8
	this.instance = new lib.Tween13("synched",0);
	this.instance.setTransform(-126.95,24.05);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(459).to({_off:false},0).to({alpha:1},20).wait(1));

	// Layer_10
	this.instance_1 = new lib.Tween14("synched",0);
	this.instance_1.setTransform(-141.45,15.55);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:0},14).to({_off:true},1).wait(465));

	// legal
	this.instance_2 = new lib.Group();
	this.instance_2.setTransform(-23.6,7,1,1,0,0,0,112.6,9.7);
	this.instance_2.alpha = 0.6992;

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag4BEQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAAAgBgBIgBgDIAAgGIABgEQABgCADgCIA4g2QAFgHACgEQACgGAAgFQAAgKgGgHQgGgHgLAAQgHAAgGAEQgGADgDAFQgDAFgBAHQAAABAAABQAAAAgBABQAAAAAAAAQgBABAAAAIgDABIgKAAIgDgBIgBgDQAAgHADgHQAEgJAFgFQAEgFAJgEQAJgEALAAQAPAAAJAGQAJAFAFAJQAEAJAAALQAAAHgCAIQgDAHgGAFQgFAHgIAHIgkAlIA7AAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAIAAAIQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAAAQAAABgBAAQAAAAAAAAQgBABAAAAQgBAAAAAAgAhjBEQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBAAAAgBIgBgDIAAhqIggAZIgDABIgDgCIgFgGIgBgEIACgCIApggIADgCIAMAAIADACIABADIAAB7IgBADIgDACgABeA9IgDgBQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAIAAgoIgnAAIgDgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAIAAgGQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAAAIAnAAIAAglIACgDQAAgBAAAAQAAAAABAAQAAAAABAAQAAAAABAAIAGAAIAEABIABADIAAAlIAnAAIADACQAAAAABAAQAAAAAAABQAAAAAAABQAAAAAAABIAAAGIgBADIgDABIgnAAIAAAoIgBADIgEABg");
	this.shape.setTransform(145.025,7.825);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance_2}]}).wait(480));

	// logo_pd_sm
	this.instance_3 = new lib.logopdsmall("synched",0);
	this.instance_3.setTransform(-76.2,-46.85,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({scaleX:1,scaleY:1},39,cjs.Ease.cubicInOut).to({scaleX:1.06,scaleY:1.06},440).wait(1));

	// grad
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#1E2130","rgba(30,33,48,0)"],[0,1],0,36.7,0,-36.7).s().p("EizRAGWIAAsrMFmjAAAIAAMrg");
	this.shape_1.setTransform(10.225,2.925);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(480));

	// _pic_1_png
	this.instance_4 = new lib.Symbol23();
	this.instance_4.setTransform(0,36.05,1,1,0,0,0,0,17.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({regY:17.2,scaleX:1.04,scaleY:1.04,y:36.1},479).wait(1));

	// text
	this.instance_5 = new lib.Tween12("synched",0);
	this.instance_5.setTransform(0,-30);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({y:-105,alpha:1},39,cjs.Ease.cubicOut).to({y:-109},440).wait(1));

	// Layer_11
	this.instance_6 = new lib.blur2();
	this.instance_6.setTransform(-14.55,232.4,0.4916,0.7454,-8.4881,0,0,-223.9,-176.8);
	this.instance_6.filters = [new cjs.BlurFilter(100, 100, 1)];
	this.instance_6.cache(-1000,-513,973,683);

	this.instance_7 = new lib.blur1();
	this.instance_7.setTransform(-84.25,239.6,0.5308,0.7976,-8.4881,0,0,-233.2,-161.2);
	this.instance_7.filters = [new cjs.BlurFilter(100, 100, 1)];
	this.instance_7.cache(-608,-565,981,718);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_7},{t:this.instance_6}]}).wait(480));

	// back
	this.instance_8 = new lib.Symbol26();

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(480));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2249.4,-175,4216,770.6);


// stage content:
(lib.indexpd1501 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0];
	this.isSingleFrame = false;
	// timeline functions:
	this.frame_0 = function() {
		if(this.isSingleFrame) {
			return;
		}
		if(this.totalFrames == 1) {
			this.isSingleFrame = true;
		}
		_main = this;
		
		window.onresize = function () {
			
			moveElements();
			
		};
		function moveElements() {
			var domOverlay = document.getElementById("dom_overlay_container");
		
			
			var nowW, nowH;
		
			nowW = nowW = window.banner.clientWidth;
		
			canvas.width = domOverlay.width = nowW * window.devicePixelRatio;
			canvas.style.width = domOverlay.style.width = nowW + "px";
			
				_main.fon.x = nowW/2;
			
				if(nowW >= 728&& nowW < 8192){
				_main.banner_big.visible = true;
				_main.banner_mini.visible = false;
				_main.banner_big.x = nowW/2;
				}
			
				if(nowW >= 320 && nowW < 728){
				_main.banner_big.visible = false;
				_main.banner_mini.visible = true;
				_main.banner_mini.x = nowW/2;
				}	
			
			};
		
		moveElements();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// big
	this.banner_big = new lib._main_1500();
	this.banner_big.name = "banner_big";
	this.banner_big.setTransform(750,125);

	this.timeline.addTween(cjs.Tween.get(this.banner_big).wait(1));

	// mini
	this.banner_mini = new lib._main_320();
	this.banner_mini.name = "banner_mini";
	this.banner_mini.setTransform(750,125);

	this.timeline.addTween(cjs.Tween.get(this.banner_mini).wait(1));

	// fon
	this.fon = new lib.Symbol4();
	this.fon.name = "fon";
	this.fon.setTransform(750,125);

	this.timeline.addTween(cjs.Tween.get(this.fon).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(2506,-206.1,493.9000000000001,1164.2);
// library properties:
lib.properties = {
	id: 'E9B8AB9FF212474ABDDFEE9BBAB6A08A',
	width: 8192,
	height: 150,
	fps: 60,
	color: "#1E2130",
	opacity: 1.00,
	manifest: [
		{src:"index_atlas_1.png", id:"index_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['E9B8AB9FF212474ABDDFEE9BBAB6A08A'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;